#include QMK_KEYBOARD_H


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */


const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT_split_3x6_3(

        KC_ESC,     KC_Q,       KC_W,       KC_E,       KC_R,       KC_T,           KC_Y,       KC_U,       KC_I,       KC_O,       KC_P,       KC_BSPC,
        KC_TAB,     KC_A,       KC_S,       KC_D,       KC_F,       KC_G,           KC_H,       KC_J,       KC_K,       KC_L,       KC_SCLN,    KC_ENT,
        KC_LSFT,    KC_Z,       KC_X,       KC_C,       KC_V,       KC_B,           KC_N,       KC_M,       KC_COMM,    KC_DOT,     KC_SLSH,    KC_RCTL,
                                        KC_LGUI, LT(3,KC_SPC), LT(4,KC_ENT),        LT(2,KC_TAB), LT(1,KC_SPC), KC_RALT
    ),

	[1] = LAYOUT_split_3x6_3(
        KC_TRNS,    KC_LBRC,    KC_7,       KC_8,       KC_9,       KC_RBRC,        KC_NO,      KC_NO,      KC_NO,      KC_NO,      KC_NO,      KC_TRNS,
        KC_TRNS,    KC_QUOT,    KC_4,       KC_5,       KC_6,       KC_EQL,         KC_NO,      KC_RSFT,    KC_RCTL,    KC_RALT,    KC_RGUI,    KC_TRNS,
        KC_TRNS,    KC_NUBS,    KC_1,       KC_2,       KC_3,       KC_GRV,         KC_NO,      KC_NO,      KC_NO,      KC_NO,      KC_NO,      KC_TRNS,
                                            KC_NO,      KC_0,       KC_MINS,        KC_NO,      KC_NO,      KC_NO
    ),

	[2] = LAYOUT_split_3x6_3(
        KC_TRNS,    KC_LCBR,    KC_AMPR,    KC_ASTR,    KC_LPRN,    KC_RCBR,        KC_NO,      KC_NO,      KC_NO,      KC_NO,      KC_NO,      KC_TRNS,
        KC_TRNS,    KC_DQUO,    KC_DLR,     KC_PERC,    KC_CIRC,    KC_PLUS,        KC_NO,      KC_RSFT,    KC_RCTL,    KC_RALT,    KC_RGUI,    KC_TRNS,
        KC_TRNS,    KC_PIPE,    KC_EXLM,    KC_AT,      KC_HASH,    KC_TILD,        KC_NO,      KC_NO,      KC_NO,      KC_NO,      KC_NO,      KC_TRNS,
                                            KC_LPRN,    KC_RPRN,    KC_UNDS,        KC_NO,      KC_NO,      KC_NO
    ),

	[3] = LAYOUT_split_3x6_3(
        KC_TRNS,    KC_NO,      KC_NO,      KC_NO,      KC_NO,      KC_NO,          KC_DEL,     KC_PSTE,    KC_COPY,    KC_CUT,     KC_UNDO,    KC_TRNS,
        KC_TRNS,    KC_LGUI,    KC_LALT,    KC_LCTL,    KC_LSFT,    KC_NO,          KC_CAPS,    KC_LEFT,    KC_DOWN,    KC_UP,      KC_RGHT,    KC_TRNS,
        KC_TRNS,    KC_SPC,     KC_NO,      KC_NO,      KC_NO,      KC_NO,          KC_INS,     KC_HOME,    KC_PGDN,    KC_PGUP,    KC_END,     KC_TRNS,
                                            KC_NO,      KC_NO,      KC_NO,          KC_NO,      KC_NO,      KC_NO
    ),

	[4] = LAYOUT_split_3x6_3(
        KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_F12, KC_F7, KC_F8, KC_F9, KC_NO, KC_TRNS,
        KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_F11, KC_F4, KC_F5, KC_F6, KC_NO, KC_TRNS,
        KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_F10, KC_F1, KC_F2, KC_F3, KC_NO, KC_TRNS,
        KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO
    )
};

#if defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {

};
#endif // defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)




